# Abstract {- #ch:abstract}

The research was motivated by the desire to understand the Australian smart meters data, which was collected half-hourly for two years at the household level. With temporal data available at ever finer scales, exploring periodicity can become overwhelming with so many possible temporal deconstructions to explore. Analysts are expected to comprehensively explore the many ways to view and consider temporal data. However, the plethora of choices and the lack of a systematic approach to do so quickly can make the task overwhelming.


<!-- exploration may be required to be carried out across both finer and coarser scales to draw useful inferences about the underlying process. It is important to be able to navigate through all the temporal deconstructions that accommodate for periodicities to have multiple perspectives of the observed data. This idea aligns with the notion of EDA (Tukey 1977) which emphasizes the use of multiple perspectives on data to help formulate hypotheses before proceeding to hypothesis testing. Slicing and dicing the data in all possible temporal scales as suggested by EDA can be a daunting task as it leads to a -->
<!-- myriad of possibilities. -->


<!-- Analysts are expected to comprehensively explore the many ways to view and consider temporal data. However, the plethora of choices and the lack of a systematic approach to do so quickly can make the task overwhelming -->


<!-- exploring periodicity can become overwhelming with so many possible temporal deconstructions to explore. Analysts are expected to comprehensively explore the many ways to view and consider temporal data. However, the plethora of choices and the lack of a systematic approach to do so quickly can make the task overwhelming. -->

<!-- <WHY> <WHAT> <HOW> -->

This work investigates how time may be dissected, resulting in alternative data segmentation and, as a result, different visualizations that can aid in the identification of underlying patterns. The first contribution (Chapter \@ref(ch:gravitas)) describes classes of time deconstructions using linear and cyclic time granularities. It provides tools to compute possible cyclic granularities from an ordered (usually temporal) index and also a framework to systematically explore the distribution of a univariate variable conditional on two cyclic time granularities by defining "harmony". "harmony" denotes pairs of granularities that could be analyzed together and reduces the search from all possible options. This approach is still overwhelming for human consumption because there would still be a huge number of harmonies. Hence, the second contribution (Chapter \@ref(ch:hakear)) refines the search of informative granularities by identifying those for which the differences between the displayed distributions are greatest and rating them in order of importance of capturing maximum variation. The third contribution (Chapter \@ref(ch:gracsr)) builds upon the first two to provide methods for exploring heterogeneities in repetitive behavior for many households and over multiple granularities. It accomplishes this by providing a way to cluster time series based on probability distributions across informative cyclic granularities. Although we were motivated by the smart meter example, the problem and the solutions we propose are practically relevant to any temporal data observed more than once per year.

<!-- there is a need to resort to clustering, which has been addressed in  It approaches the problem by computing pairwise distances between time series based on probability distributions over multiple cyclic granularities at once. -->
\newpage
