# Introduction {#ch:intro}

<!-- Introduction -->
<!-- Motivation & Background -->
<!-- Outline of the thesis -->

<!-- To tame the complexity of time, breaking it into years, months, weeks, days and so on in a hierarchical manner is a common way to relate data to time. Such dicrete human made abstractions of time can be thought of as time granularities.(Aigner et al., 2008). -->

<!-- outline the intro chapter structure -->

<!-- This chapter provides an introduction to the study by first discussing the background and context, followed by the overarching research aim and objectives, each of which correspond to each chapter in this thesis. -->

<!-- Background -->

The Smart Grid, Smart City (SGSC) project (2010–2014) available through the [Department of the Environment and Energy](https://data.gov.au/data/organization/doee) provides half-hourly data of over 13,000 Australian electricity smart meter customers distributed unevenly from October 2011 to March 2014. Large data sets like this include significant uncertainty regarding customer behavior due to the rising variety of customers. Behavioral patterns vary significantly due to differences in size, location, and amenities such as solar panels, central heating, and air conditioning. For example, some families use a dryer, while others hang their clothes to dry. This could be reflected in their weekly profile. They may vary on a monthly basis, with some customers using more air conditioners or heaters than others despite having comparable electrical equipment and weather conditions. Some customers are night owls, while others are morning larks, which may show up in their daily profile. Customers' day-off energy consumption varies depending on whether they stay at home or go outside. 

<!-- introducing the overall field-->
With the availability of data at more and more finer time scales, exploration of time series data may be required to be carried out across both finer and coarser scales to draw useful inferences about the underlying process. To reduce the complexity of time, it is typical to divide it into years, months, weeks, days, and so on in a hierarchical manner [@aigner2011visualization]. These discrete abstractions of time are known as time granularities. Linear time granularities [@Bettini1998-ed] ,such as hours, days, weeks and months, respect the linear progression of time and are non-repeating. Cyclic temporal granularities representing cyclical repetitions in time (such as hour-of-the-day, work-day/weekend) are effective for analyzing repetitive patterns in time series data.


To acquire a comprehensive view of the repeated patterns, it is necessary to navigate through all of the conceivable cyclic granularities. This approach is consistent with the concept of EDA [@Tukey1977-jx], which stresses the utilization of multiple perspectives on data to assist formulate hypotheses before proceeding to hypothesis testing. This, however, is a challenging process since it throws up a myriad of alternatives. Furthermore, the transition from linear to cyclic granularities results in restructured data, with each level of the temporal deconstruction corresponding to multiple values of the observed variable. This motivates the research presented in this thesis, which aims to provide a platform for systematically exploring probability distributions induced by these multiple observations to support the discovery of regular patterns or anomalies, as well as the exploration of clusters of behaviors or the summarization of the behavior.



<!-- There could potentially be many, many ways to analyze the data across cyclic granularities. -->


<!-- For example, data collected at an hourly scale could be analyzed using coarser temporal scales such as days, months or quarters. This approach requires deconstructing time in various possible ways. Moreover, it might often be interesting to capture calendar or periodic effects like month-of-year, day-of-week, or hour-of-day. They help us answer questions like if certain levels of those time deconstructions are characterized by unusual/typical values of the observed variable. For example, certain days of the week or months of the year are likely to be characterized by higher values. Visualizations using linear time granularities are often ineffective in conveying repetitive behaviors because multiple observations are squeezed together in that representation. Hence, we define cyclic granularities for exploring repetitive patterns. There could potentially be many, many cyclic granularities to explore. It is essential to navigate through all the options to get a comprehensive view of the repeated patterns. This idea aligns with the notion of EDA (Tukey 1977), which emphasizes the use of multiple perspectives on data to help formulate hypotheses before proceeding to hypothesis testing. -->

<!-- introduce the specific problem  -->
<!-- ## change in data structure as a result of transitioning from linear to cyclic deconstructions -->
<!-- + Existing approaches, why we need to drill down, or why we want to -- probability distributions -->



<!-- My contribution in this thesis is to explore probability distributions induced by these multiple observations to better understand heterogeneity in repetitive behavior that can arise across temporal dependencies. -->


<!-- Summarizing the probability distribution of these multiple observations to capture both shape and uncertainty could be a potential approach to understanding the underlying distribution of these observations.  -->

<!-- Hence, the overarching research goal is to study the periodic behavior of temporal data in a structured way by studying the probability distributions by best exploiting the characteristics of time. -->




<!-- Following research objectives would facilitate the achievement of this aim -->
<!-- Research objectives -->

<!-- ## Research aims -->


<!-- The first part of the work discusses computation of all possible combinations of cyclic time granularities and a graphical mapping such that distributions of a numeric response variable is displayed across combinations of two cyclic granularities. Even analyzing the distribution of the measured variable across two cyclic granularities at once could amount to displaying many plots in search of potential  patterns. Thus, the first part of the research also introduces "harmony" to denote pairs of granularities that could be analyzed together and reduces the search from all possible options. But this approach is still overwhelming for human consumption because there would still be huge number of harmonies. Hence, the second part of the research extends this work and narrows the search further by finding pair of cyclic granularities which are informative enough and rank them according to their importance. However, to explore periodic patterns of many households, we have to resort to clustering which has been addressed in the third part of the research. Although the motivation came through the smart meter example, this is a problem that is relevant to any temporal data observed more than once per year. -->

## Visualizing probability distributions across bivariate cyclic temporal granularities {#sec:gravitas}
  
  Deconstructing a time index into time granularities can assist in exploration and automated analysis of large temporal data sets. This paper describes classes of time deconstructions using linear and cyclic time granularities. Linear granularities respect the linear progression of time such as hours, days, weeks and months. Cyclic granularities can be circular such as hour-of-the-day, quasi-circular such as day-of-the-month, and aperiodic such as public holidays. The hierarchical structure of granularities creates a nested ordering: hour-of-the-day and second-of-the-minute are single-order-up. Hour-of-the-week is multiple-order-up, because it passes over day-of-the-week. Methods are provided for creating all possible granularities for a time index. A recommendation algorithm provides an indication whether a pair of granularities can be meaningfully examined together (a "harmony"), or when they cannot (a "clash").  
   
   Time granularities can be used to create data visualizations to explore for periodicities, associations and anomalies. The granularities form categorical variables (ordered or unordered) which induce groupings of the observations. Assuming a numeric response variable, the resulting graphics are then displays of distributions compared across combinations of categorical variables.  
    
   The methods implemented in the open source R package `gravitas` are consistent with a tidy workflow, with probability distributions examined using the range of graphics available in `ggplot2`.

 <!-- This chapter contains a literature review related to linear granularities. -->
 
## Detecting distributional differences between temporal granularities for exploratory time series analysis {#sec:hakear}

This work is a natural extension of Chapter \@ref(ch:gravitas). Many, many other displays might be built using different granularities, such as day-of-week, day-of-month, weekday/weekend, and so on. However, only a handful of them may be interesting, revealing major patterns. Determining which displays exhibit "significant" distributional differences between cyclic granularity categories and plotting only these would allow for more efficient exploration. Furthermore, a few of the displays in this collection will be more engaging than others. This chapter provides a new distance metric for selecting and ranking the multiple granularities. The statistical significance of potential visual discoveries is aided by selecting a threshold for the proposed numerical distance measure. The distance measure is computed for a single or pairs of cyclic granularities, and it can be compared across different cyclic granularities as well as a collection of time series. This chapter also includes a case study using residential smart meter data from Melbourne to demonstrate how the suggested methodology may be utilized to automatically find temporal granularities with significant distributional differences. The methods are implemented in the open-source R package 'hakear.'

## Clustering time series based on probability distributions across temporal granularities {#sec:gracsr}

In this chapter, we look at the problem of using clustering to discover patterns in a large number of univariate time series across multiple temporal granularities. Time series clustering research is gaining traction as more data is collected at finer temporal resolution, over longer time periods, and for a larger number of individuals/entities. Many disciplines have noisy, patchy, uneven, and asynchronous time series that make it difficult to search for similarities. We propose a method for overcoming these constraints by calculating distances between time series based on probability distributions at various temporal granularities. Because they are based on probability distributions, these distances are resistant to missing or noisy data and aid in dimension reduction. When fed into a clustering algorithm, the distances can be used to divide large data sets into small pockets of similar repetitive behavior. These subgroups can then be analyzed separately or used as distinct prototype behaviors in classification problems. The proposed method was tested on a group of residential electricity consumers from the Australian smart meter data set to show that it can generate meaningful clusters. This chapter includes a brief review of the literature on traditional time series clustering and, more specifically, clustering residential smart meter data.



<!-- Time series clustering research is gaining a lot of importance with more and more time series data recorded at much finer temporal resolution, for a longer period of time and for a larger number of individuals/entities.Similarity searches amongst these long time series are often limited by the type of noisy, patchy, unequal and asynchronous time series common in many fields. In this paper we propose a strategy to alleviate these limitations by  clustering time series based on probability distributions across cyclic temporal granularities. Cyclic granularities are temporal deconstructions of a time period into units such as hour-of-the-day, work-day/weekend, which can be useful for measuring repetitive patterns in large univariate time series data. Thus, looking at the probability distributions across cyclic granularity leads to a method which is robust to missing or noisy data, helps in dimension reduction while ensuring small pockets of similar repetitive behaviors. The method is applied to electricity smart meter dat -->
<!-- The suggested approach was evaluated on a set of benchmark time series on residential electricity customers. The empirical results show that our approach is able to yield meaningful clusters. -->

## Summary

The thesis is structured as follows. Chapter \@ref(ch:gravitas) provides details of the cyclic granularities, different classes, and computation, and also its usage in exploratory time series analysis through applications. This is implemented in the R package **gravitas**. Chapter \@ref(ch:hakear) provides guidance on how to choose significant cyclic granularities, which are likely to have interesting patterns across its categories. This is available as the R package **hakear**. The chapter @ref (ch: gracsr) provides similarity measures for comparing multiple time series.This is in the developing R package **gracsr**. Chapter \@ref(ch:conclusion) summarizes the software tools developed for the work, and discusses some future plans.
